mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls),
    path("product/", include('product.urls', namespace='product')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import (
    ProductListView,
    ProductDetailView,
    OrderView,
    ThankYouView,
)

app_name = "product"
urlpatterns = [
    path("", ProductListView.as_view(), name="product-list"),
    path("<int:pk>/detail/", ProductDetailView.as_view(), name="product-detail"),
    path("<int:pk>/detail/order/", OrderView.as_view(), name="product-order"),
    path("<int:pk>/detail/order/thank-you/", ThankYouView.as_view(), name="thank-you"),
] 
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products')
    
    def __str__(self):
        return f"{self.id}. {self.name}. {self.image}"
    
    
class Order(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    quantity = models.PositiveIntegerField(default=0)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    # Tambahkan bidang-bidang lain yang diperlukan untuk pesanan

    def __str__(self):
        return self.full_name

product/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "full_name",
            "email",
            "address",
            "city",
            "postal_code",
            "quantity",
            "total_amount",
        ]

product/views.py
import paypalrestsdk
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from .models import Product
from .forms import OrderForm
from django.views.generic import (
    ListView,
    DetailView,
    FormView,
    TemplateView,
)

class ProductListView(ListView):
    model = Product
    template_name = 'product/product_list.html'
    context_object_name = 'products'


class ProductDetailView(DetailView):
    model = Product
    template_name = "product/product_detail.html"
    context_object_name = 'product'
    
    
class OrderView(FormView):
    template_name = 'product/product_order.html'
    form_class = OrderForm
    success_url = 'thank-you/'  # URL untuk halaman setelah berhasil checkout
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = Product.objects.get(pk=self.kwargs['pk'])  # Ganti dengan logika pengambilan produk yang sesuai
        context['price'] = product.price
        return context

    def form_valid(self, form):
        # Simpan instance Order ke database menggunakan ModelForm
        self.order = form.save()
        # return super().form_valid(form)

        # Proses pembayaran menggunakan PayPal
        paypalrestsdk.configure({
            "mode": "sandbox",  # Ganti dengan "live" jika sudah di produksi
            "client_id": "AW324B4Y4NbZXj6vfGSDic0v6MY_9V-xqEsYfy_6Wa-vuv2P-70cXTez2enxJlsf9nVJz7jIDIIVJuHV",
            "client_secret": "EDsBzYdVYXeKbNkeks74gcz6-KoEONyOVQxseIOOzjAAle-x8GOOh41oXqGz8uv0xr1L0IrW7weTnFNU"
        })

        # Buat objek pembayaran PayPal
        payment = paypalrestsdk.Payment({
            "intent": "sale",
            "payer": {
                "payment_method": "paypal"
            },
            "redirect_urls": {
                "return_url": self.request.build_absolute_uri(self.get_success_url()),
                "cancel_url": self.request.build_absolute_uri(self.get_cancel_url())
            },
            "transactions": [
                {
                    "amount": {
                        "total": str(self.order.total_amount),  # Total pembayaran dari order
                        "currency": "USD"  # Ganti dengan mata uang yang sesuai
                    },
                    "description": "Deskripsi pembayaran"  # Deskripsi pembayaran yang ingin ditampilkan
                }
            ]
        })

        # Buat pembayaran PayPal
        if payment.create():
            # Redirect pengguna ke halaman pembayaran PayPal
            for link in payment.links:
                if link.method == "REDIRECT":
                    redirect_url = str(link.href)
                    return HttpResponseRedirect(redirect_url)
        else:
            # Handle jika pembuatan pembayaran gagal
            # Misalnya, tampilkan pesan kesalahan atau redirect kembali ke halaman checkout
            return super().form_invalid(form)
        
    def get_cancel_url(self):
        pk = self.kwargs['pk']  # Mendapatkan nilai pk dari argumen URL
        return reverse_lazy('product:product-order', kwargs={'pk': pk})


    def form_invalid(self, form):
        # Handle jika form checkout tidak valid
        # Misalnya, tampilkan pesan kesalahan atau redirect kembali ke halaman checkout
        return super().form_invalid(form)

class ThankYouView(TemplateView):
    template_name = 'product/thank_you.html'
    

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Website Penjualan</title>
    {% include 'snippets/styles.html' %}
    <style>
      .product-card {
          cursor: pointer;
          transition: transform 0.3s ease; box-shadow 0.3s ease;
      }
  
      .product-card:hover {
          transform: scale(1.05);
          box-shadow: 0 8px 12px rgba(0, 0, 0, 0.1);
      }
  </style>
  </head>
  <body style="min-height: 1000px;">
    {% comment %} Navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-primary navbar-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Mineralpedia</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'product:product-list' %}">Product</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact me</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% comment %} Navbar end {% endcomment %} 
    <div class="container" style="padding-top: 6rem;">
      {% block content %} 
      
      {% endblock %}
    </div>
    <footer>
      <!-- Footer content goes here -->
    </footer>
    {% include 'snippets/scripts.html' %}
    <script>
      // Ambil semua elemen dengan kelas "product-card"
      var productCards = document.querySelectorAll('.product-card');
  
      // Tambahkan event listener pada setiap elemen
      productCards.forEach(function(card) {
          card.addEventListener('click', function() {
              // Ambil URL detail produk dari atribut href pada elemen "a" di dalam "product-card"
              var productDetailUrl = this.querySelector('a').getAttribute('href');
              
              // Navigasikan ke halaman detail produk
              window.location.href = productDetailUrl;
          });
      });
  </script>
  </body>
</html>

templates/product/product_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="container text-center">
    <div class="row">
        <div class="col mb-3">
            <h3>Detail Product</h3>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <img src="{{product.image.url}}" class="card-img-top" alt="{{product.name}}">
                <div class="card-body">
                  <h5 class="card-title">{{product.name}}</h5>
                  <p class="card-text">{{product.description}}</p>
                  <p>{{product.price}} | <a href="{% url 'product:product-order' product.pk %}" class="btn btn-primary">Order Now</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
    

templates/product/product_list.html
{% extends 'base.html' %}


{% block content %}
<div class="container text-center">
    <div class="row d-flex justify-content-center">
        {% for product in products %}
            <div class="col-6 col-lg-4 product-card">
                <a href="{% url 'product:product-detail' product.pk %}" style="text-decoration: none;">
                    <div class="card m-4">                
                        <img src="{{product.image.url}}" class="card-img-top" alt="{{product.name}}" width="300">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title" style="color: black;">{{product.name}}</h5>
                    </div>
                </a>                   
            </div>
        {% endfor %}           
    </div>
</div>
{% endblock content %}




    

     

        

templates/product/product_order.html
{% extends 'base.html' %}


{% block content %}
<div class="container text-center">
    <div class="row">
        <div class="col mb-2">
            <h2>Order Page</h2>
        </div>
    </div>
    <div class="row">
        <div class="col d-flex justify-content-center">
            <form method=POST>
                {% csrf_token %}
                <table>
                    {{form.as_table}}
                </table>
                <br>
                <button class="btn btn-primary" type="submit">Checkout</button>
            </form>
            <script>
                // Mengambil elemen bidang quantity dan total_amount
                const quantityInput = document.getElementById('id_quantity');
                const totalAmountInput = document.getElementById('id_total_amount');
                const price = {{ price }};  // Mendapatkan harga dari konteks
            
                // Menambahkan event listener untuk perubahan nilai pada bidang quantity
                quantityInput.addEventListener('change', () => {
                    // Mengambil nilai quantity
                    const quantity = parseFloat(quantityInput.value);
            
                    // Menghitung total_amount
                    const totalAmount = quantity * price;
            
                    // Menetapkan nilai total_amount pada input field
                    totalAmountInput.value = totalAmount.toFixed(2);
                });
            </script>
        </div>
    </div>
</div>
    

{% endblock content %}
    

templates/product/thank_you.html
{% extends 'base.html' %}

{% block content %}
  <h1>Thank You!</h1>
  <p>Your order has been successfully placed.</p>
{% endblock %}

templates/snippets/scripts.html
{% load static %}

<script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>

templates/snippets/styles.html
{% load static %}

<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">